name: Deploy documentation to Pages

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout documentation
        uses: actions/checkout@v4
        with:
          repository: wx2020/easytier-doc
          path: docs
          submodules: recursive

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
          cache-dependency-path: docs/pnpm-lock.yaml

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Install dependencies
        working-directory: docs
        run: pnpm -r install --frozen-lockfile

      - name: Build documentation
        working-directory: docs
        env:
          VITEPRESS_BASE: /easytier/
        run: pnpm docs:build

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: docs/.vitepress/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Pages
        id: deployment
        uses: actions/deploy-pages@v4
